### ISSUE TITLE
Enhancement: Using lightweight CSS

### ISSUE THREAD

**Issue by DonaldTsang** [catamphetamine/captchan#1]
I would recommend https://purecss.io/ as it is popular and super light.
Others: 
- https://tutorialzine.com/2018/05/10-lightweight-css-frameworks-you-should-know-about
- http://www.creativeweblogix.com/blog/12-lightweight-css-frameworks
- https://speckyboy.com/responsive-lightweight-css-frameworks/
- https://dzone.com/articles/top-10-lightweight-css-frameworks-for-building-fas
- https://catswhocode.com/css-frameworks/
- https://pagestead.com/blog/the-best-lightweight-css-frameworks-in-2018/
- https://www.somewhatcreative.net/development/css/10-of-the-best-lightweight-css-frameworks-for-developers/

**Comment by DonaldTsang** [comment]
Right now the Bootstrap-looking CSS uses too large of a font, and the rounded corners kind of makes it look too "un-modern" when compared to PureCSS's sharp edges. Maybe have a look at https://material.io/design/ (I am against Google but the looks of the site needs to be redesigned)

**Comment by catamphetamine** [comment]
Hi.
Thanks for the links but I don't think we'll be switching the UI library.
And the current design stays as is.
On the settings page there's the ability to add custom themes.
There one can add any arbitrary CSS like resetting `border-radius`, changing paddings/margins, etc.
