### ISSUE TITLE
Enhancement: 8chan/lynxchan board search on board bar

### ISSUE THREAD

**Issue by DonaldTsang** [catamphetamine/captchan#2]
iIf the black bar on the left allows for direct search instead of needing to click "Show All Boards" that would be convenient.

**Comment by catamphetamine** [comment]
Hello.
Yeah, I guess that would be a convenient feature.
Will be implemented, maybe by September or so.

**Comment by DonaldTsang** [comment]
Okay, so maybe we can brainstorm some new feautures while we have the time

**Comment by catamphetamine** [comment]
I have a looot of features planned.
But I only write code in free time when I have the mood and when I'm not writing my other open-source projects, so this app is planned for finish somewhere by the end of this year.

**Comment by catamphetamine** [comment]
The TODO list FYI.
Mostly in Russian.

https://github.com/catamphetamine/captchan/blob/master/TODO.md

The next features will be:

* Adding threads to the list of tracked ones.
* Adding message posting.

I guess those two will ships somewhere in Autumn.

**Comment by DonaldTsang** [comment]
Okay so lynxchan is the most famous in https://endchan.xyz and https://waifuist.pro

**Comment by catamphetamine** [comment]
https://endchan.xyz seems like funny one, mostly Russian for some reason, but it's inactive too. [Added it](https://catamphetamine.github.io/captchan/?chan=endchan). Just the basic message syntax: seems that they even allow [rainbow-colored text](https://endchan.xyz/.static/posting.html). Runs a [really old](https://endchan.xyz/index.json) version of `lynxchan` though: `1.7.5`. But seems to work (only briefly checked it).

https://waifuist.pro looks like a creepy/perv one, lol.

**Comment by DonaldTsang** [comment]
@catamphetamine I could have thrown in bbw-chan.nl but that is way too gross to be included.

**Comment by catamphetamine** [comment]
@DonaldTsang Oh shoot, they even got that )

**Comment by catamphetamine** [comment]
Added board search in sidebar ("Boards" -> "..." -> type board id or title).

![image](https://user-images.githubusercontent.com/477167/65365579-2db03700-dc23-11e9-88c7-0c1d9ed74c6f.png)

**Comment by DonaldTsang** [comment]
Thanks!
