### ISSUE TITLE
Code syntax highlighting

### ISSUE THREAD

**Issue by catamphetamine** [catamphetamine/captchan#4]
As discussed in the [`arisuchan` and `lainchan`](https://github.com/catamphetamine/captchan/issues/3) issue, those two chans have code syntax highlighting.

The markup is already generated as a standard one:

```html
<pre>
  <code class="language-...">
    ...
  </code>
</pre>
```

A code highlighter could be included on a page.
For example, [Prism](https://prismjs.com).

There's an [Autoloader](https://prismjs.com/plugins/autoloader/) plugin that loads syntaxes dynamically.

```html
<!DOCTYPE html>
<html>
<head>
	...
	<link href="https://cdn.jsdelivr.net/npm/prismjs@1.x/themes/prism.css" rel="stylesheet" />
</head>
<body>
	...
	<script src="https://cdn.jsdelivr.net/npm/prismjs@1.x/prism.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/prismjs@1.x/plugins/autoloader/prism-autoloader.min.js"></script>
	<script>Prism.plugins.autoloader.languages_path = 'https://cdn.jsdelivr.net/npm/prismjs@1.x/components/'</script>
</body>
</html>
```

That would be Prism, but by default it only highlights code (and loads syntaxes) on page load.
React is different — it renders stuff after page load, so there should be a way to re-run Prism highlighter after the code component has rendered.

There seems to be a React wrapper for Prism that does the dynamic re-running thing:
https://github.com/FormidableLabs/prism-react-renderer

**Comment by DonaldTsang** [comment]
Notes on 8/tech/?

**Comment by catamphetamine** [comment]
What about it?

**Comment by DonaldTsang** [comment]
About how 8chan also has code tags for scripts

**Comment by catamphetamine** [comment]
I visited 8ch.net and looked at the `/tech/` board.
Seems like standard non-highlighted syntax.

```html
<pre class="prettyprint prettyprinted" style="display: inline-block;"><code></code></pre>
```

There seems to be no AI included to autodetect a language.
https://github.com/PrismJS/prism/issues/1313

So unless a chan explicitly sets the `language` on `<pre/>` or `<code/>` it won't be highlighted by the highlighter.
`8ch.net` seems to not set the explicit `language` on `<pre/>` or `<code/>`.
So I guess `8ch.net` wouldn't support syntax highlighting.

![image](https://user-images.githubusercontent.com/477167/61579173-799f0c80-ab0a-11e9-9bd3-291a1f228217.png)

**Comment by DonaldTsang** [comment]
@catamphetamine try typing this into the post
```
[code]python
x = 42
[/code]
[code]c
int x = 42
[/code]
```
and see what happens next

**Comment by catamphetamine** [comment]
@DonaldTsang Well, on the screenshot above I can see that it has highlighted C but it doesn't provide the `language` info anywhere so it's underiveable I guess.
And `8ch.net` engine seems to not having been maintained for a couple of years now so I guess there won't be such a feature.
Only some kind of an AI could autodetect a language I guess.

**Comment by catamphetamine** [comment]
Note to self:

Seems that the original `Prism` library is made for highlighting syntax on page load while React rendering is different.

There seems to be a library called [`react-syntax-highlighter`](https://www.npmjs.com/package/react-syntax-highlighter) that's based on some other libraries that are based on `Prism` and `highlight-js`.

The library supports both loading new language syntaxes on demand (asynchronously) and even loading Prism library core itself (about 20kB gzipped) asynchronously.

https://www.npmjs.com/package/react-syntax-highlighter#async-build

```js
import { PrismAsyncLight as SyntaxHighlighter } from 'react-syntax-highlighter';
```

A language could be checked for support using `SyntaxHighlighter.supportedLanguages`.

If the language is supported then it could be checked for being loaded via `SyntaxHighlighter.isLanguageRegistered('...')`.

If the language hasn't been loaded yet then it can be loaded ("registered"):

```js
import jsx from 'react-syntax-highlighter/dist/esm/languages/prism/jsx';

// It's not clear what is this line for.
import prism from 'react-syntax-highlighter/dist/esm/styles/prism/prism';
 
SyntaxHighlighter.registerLanguage('jsx', jsx);
```

How could a language syntax be loaded at runtime rather than being included in a bundle?
I guess something like `fetch()`ing the language syntax from `unpkg.com` would work (seems that they allow CORS), and then such "raw" javascript could be wrapped in `SyntaxHighlighter.registerLanguage()` and inserted on a page as a `<script/>` tag and then the React component showing the code should be somehow re-rendered completely (maybe with another `key` or something).

**Comment by catamphetamine** [comment]
Hmm, I guess it kinda works.
Not for `8ch.net` though, because it doesn't tell the `language`.
But for `lainchan`/`arisuchan` it would I guess.

![image](https://user-images.githubusercontent.com/477167/61581993-060ef680-ab2e-11e9-8837-4fc204a51198.png)

**Comment by DonaldTsang** [comment]
In that case it shows how lain/arisu is better

**Comment by catamphetamine** [comment]
@DonaldTsang deployed on `gh-pages`. Closing.

`lainchan` works:

https://catamphetamine.github.io/captchan/%CE%BB/13961?chan=lainchan

`arisuchan` won't work because it doesn't provide the `language`.
It does have the language on a rendered HTML page but the JSON API doesn't provide the `language`:

https://arisuchan.jp/λ/res/37.html

HTML page response:

![image](https://user-images.githubusercontent.com/477167/61584785-42564d00-ab56-11e9-873f-e8df77e960d5.png)


JSON API response `com`:

```html
<pre class='block'><code class='block '>#!/usr/bin/ruby↵require
```

> In that case it shows how lain/arisu is better

Yeah, those two have been crafted with passion.
Especially `arisuchan` which is supercool.

**Comment by catamphetamine** [comment]
Ahh, I guess I see what's the reason: `arisuchan` most likely uses `highlight.js`'s autodetect feature which requires all syntaxes to be loaded which is not an option.
