### ISSUE TITLE
Enhancement:: Larger array of imageboard support

### ISSUE THREAD

**Issue by DonaldTsang** [catamphetamine/captchan#5]
http://allchans.org/ has a big list of active imageboard
https://encyclopediadramatica.rs/List_of_*chan_boards has historical records on which are "alive"

Example
- https://7chan.org/
- https://desuchan.net/

**Comment by catamphetamine** [comment]
Thx for the suggestions.
I guess having 8 demo chans is enough for now.
That's a lot, actually.
These two you listed do still work but seems like almost no one posts there anymore.
This, and also most chans that aren't based on `vichan`/`lynxchan` are based on some pre-JSON-era engines that don't support any JSON API so even if someone would attempt to add those chans to `captchan` it wouldn't even be possible.

**Comment by catamphetamine** [comment]
I'll close this for now.

**Comment by DonaldTsang** [comment]
@catamphetamine update for larger lists (taking notes, not requesting)
- https://github.com/megapro17/Dashchan#forums
- https://github.com/miku-nyan/Overchan-Android/blob/master/Imageboards.md

Has anyone made a list of sites-to-engines cheatsheet so we can do comparisons?
